apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 050752620342.dkr.ecr.us-east-1.amazonaws.com/flask-k8s-demo:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ecr-registry

